name = "gameday-worker"
account_id = "7e32b34a4c1bfd168cd4132055b1505b"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "gameday-db"
database_id = "8f36b1b1-3b21-47f5-aeb0-90033908bf51"

[vars]
CORS_ORIGIN = "https://gameday-b2x.pages.dev"

# Secrets (sæt med: wrangler secret put JWT_SECRET)
# JWT_SECRET
# HOLDSPORT_USER
# HOLDSPORT_PASS
